### ISSUE TITLE
License

### ISSUE THREAD

**Issue by snh** [rs1729/RS#17]
Hello from a fellow radiosonde enthusist!

I noticed that there doesn't appear to be a license clearly defined for this amazing repository.

For those who'd like to use, incorporate, and/or contribute back to the great work that has been done here with these radiosonde decoders, it'd be a big help if this repository was available under an open source license.

GitHub have some [documentation available](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) that guides you through adding a license to an existing repository if this is something you are interested in doing.

Thank you @rs1729 and any other contributors to this project for all your work!

**Comment by rs1729** [comment]
Thank you!
This repository was not meant to be a software project, it is more about the information I wanted to share, more like a notebook.
For projects like radiosonde_auto_rx I suggested a separate repository (only the necessary sources for decoding) that could be developed in a certain direction. radiosonde_auto_rx uses GPL v3? I believe that would be also the right license I would choose, although I never thought I would have to think about that...
For this repository I never feel comfortable about feature requests or contributions that I don't really care about. Perhaps I should make another repository with the basic decoders and a license, so it is easier for others to use the code in the sense of "open source"?

**Comment by snh** [comment]
@rs1729 No worries 😄

I wouldn't worry about feeling like you would be obligated to respond to feature requests or contributions if you were to add a license to this existing repository. The main benefit I see is helping to remove doubt or uncertaintity regarding your wishes regarding use of the content of this repository.

Your suggestion of a new repository that just contains the basic decoders, for example the ones being used by `radiosonde_auto_rx` sounds like it could be useful. That could then be used as the authoritive source for development and collaboration on those decoders, leaving this repository as your personal notebook. I still see value in adding a license to this _notebook_ repository too though regardless to clarify the situation, but it is of course your decision, and I don't want you to feel pressured in any way!

**Comment by daniestevez** [comment]
Hi @rs1729,

Thanks for your wonderful repository and sorry for jumping in on this discussion.

The main issue about not including any license with your project is that by doing so it is effectively protected by default copyright laws. This actually prevents other people from using your code at all. Probably not what you intended.

Probably licensing this as GPLv3 is a good idea. I use GPLv3 for my Jupyter notebooks just in case someone is interested in using them (but mainly these are notebooks I keep for my own experiments, whereas RS is used by many people).

In case you don't want to complicate with licenses and you don't care at all what other people do with your code, you can take a look at Public Domain and the Unlicence. These put no restrictions at all in the use others do of your code, and allow your code to be integrated in other open source projects.

**Comment by rs1729** [comment]
> The main issue about not including any license with your project is that by doing so it is effectively protected by default copyright laws. This actually prevents other people from using your code at all. Probably not what you intended.

Yes, I know... now ;-) got interested in this topic only when @snh brought up this topic... 
And I also think GPLv3 is what I would choose.

So let's try... Ok, I think it was added now.

@daniestevez 
and thanks for appreciation. your blog and repository is also very interesting to read.

**Comment by snh** [comment]
@daniestevez Thanks for jumping in and adding your insight!

@rs1729 Thanks for adding a license ❤️, and thank you again for all your work! I'll go ahead and close this issue now.

**Comment by daniestevez** [comment]
Thanks @rs1729 !
