### ISSUE TITLE
Inclusion in another project

### ISSUE THREAD

**Issue by danijelt** [rs1729/RS#19]
Not really an issue. I just want to thank you for adding GPLv3 license as it will make my life much easier.

I created sonde tracker for RPi last summer, written in Qt: https://github.com/danijelt/sondepi-qt
It's also licensed under GPLv3, so your licensing will allow me to integrate your code directly instead of the current solution, which will make the Android port much simpler.

I'll keep you updated, if interested.

**Comment by rs1729** [comment]
Thank you for notification.
