### ISSUE TITLE
build system

### ISSUE THREAD

**Issue by pinkavaj** [rs1729/RS#2]
Hi,

I found no instruction how to build individual tools and no anny build system is preset. How do you build those tools? Would you like to include anny?

I can help with that, if you wat so.

**Comment by rs1729** [comment]
The decoders are very simple to compile. Some of the decoders need math.h (compile with -lm), so you can always compile "gcc decoder.c -lm -o decoder". First I will try to make a file list/description in each directory together with some usage info like this:
https://github.com/rs1729/RS/blob/master/rs92/README.md

**Comment by pinkavaj** [comment]
This is cool and helps a lot. Would you mind if I add simple Makefiles and create pull request?

**Comment by rs1729** [comment]
I don't think these small programs need Makefiles.
Maybe I should create a new project first (was thinking about it anyway), where the decoders are separated modules processing only the raw data. For most of the decoders, signal processing/demodulation and output is very similar. That way it would be easier to add more signal processing or GUI and so on. It would be easier if someone wants to participate.

**Comment by rs1729** [comment]
Maybe the rs92-module in RS/rs_module is more readable, if you are interested in rs92/GPS.
Look at rs_rs92.c and rs_gps.c.
