### ISSUE TITLE
RS41 sgp or sg with ozone sensor

### ISSUE THREAD

**Issue by JRus-design** [rs1729/RS#20]
Hi good day from Spain,

There are possibility to implement the decoding of the aux data from the ozone sonding when the Rs41 is launched with the OIF411 ozone interface in according with Vaisala documentation M211486EN-C?

![Measurement Data](https://user-images.githubusercontent.com/57267080/80365588-22dc1580-8888-11ea-8e0d-bfaff48363b9.JPG)
![ID Data 1](https://user-images.githubusercontent.com/57267080/80365611-2e2f4100-8888-11ea-94e1-f20a1e9a02cd.JPG)
![ID Data 2](https://user-images.githubusercontent.com/57267080/80365630-34bdb880-8888-11ea-9b3e-bd879c3f53b0.JPG)
![Low temp](https://user-images.githubusercontent.com/57267080/80365676-469f5b80-8888-11ea-9e87-4e054580b28e.PNG)
![No battery   low temp](https://user-images.githubusercontent.com/57267080/80365697-4f902d00-8888-11ea-971d-d8f71c59da11.PNG)
![No battery](https://user-images.githubusercontent.com/57267080/80365710-5454e100-8888-11ea-901e-bc3f2df967d2.PNG)
![Nominal](https://user-images.githubusercontent.com/57267080/80365719-56b73b00-8888-11ea-8845-085092c70adf.PNG)

 See attached screenshots. Also I give info about the Status (Diagnostic Word) implemented with my help in the Diego IW1GIS RS41 Tracker.

**Comment by rs1729** [comment]
Yes, I know Vaisala M211486EN-C:
https://github.com/rs1729/RS/blob/35136f908f41a397d66d9508d383e20328d78097/demod/mod/rs41mod.c#L791-L793
I didn't have plans to decode the raw aux data. Also sometimes there are several instruments attached to the RS41 (have seen up to 3 aux-strings per frame); don't know if this wouldn't be too much output. Maybe it could be optional similar to the sat data.
Will think about it.

**Comment by JRus-design** [comment]
Yes, some stations, like Payerne (CH), can launch several instruments connected in chain, normally the first is OIF411 Ozone sensor from Vaisala (Id05), and connected to it the Cobald Backscatter Aerosol Detector or to the Cryogenic Frostpoint Hygrometer. Each sensor has an identifier and a chain number in the Xdata packet. 
Attached documents to decode Cobald Backscatter Aerosol Detector (Id19) & daisy chain sensor connection.
[GRUAN-TN-8_GRUAN-Monitor-MW41_01.pdf](https://github.com/rs1729/RS/files/4567272/GRUAN-TN-8_GRUAN-Monitor-MW41_01.pdf)
[CobaldOperationInstructions2017.pdf](https://github.com/rs1729/RS/files/4567263/CobaldOperationInstructions2017.pdf)
[iMet-1-RSB Radiosonde XDATA Daisy Chaining.pdf](https://github.com/rs1729/RS/files/4567264/iMet-1-RSB.Radiosonde.XDATA.Daisy.Chaining.pdf)

**Comment by rs1729** [comment]
AUX data processing should be placed in a separate module.

**Comment by LukePrior** [comment]
A JavaScript approach for XDATA decoding can be found here: https://github.com/projecthorus/sondehub-tracker/blob/testing/js/xdata.js

**Comment by rs1729** [comment]
Added basic xdata decoding, ID=0x05 (OIF411) and ID=0x01.
https://github.com/rs1729/RS/commit/99d0425a66f25c31299bfb80e1aeb9c1276ff870

**Comment by rs1729** [comment]
ID=0x08 CFH (Cryogenic Frost Point Hygrometer)
@LukePrior 
You don't have information on this?
In https://www.gruan.org/gruan/editor/documents/gruan/GRUAN-TD-5_MeiseiRadiosondes_v1_20180221.pdf
on (p.95) it says
```
Table A.1: An example of the ASCII data format of the CFH sensor, for the case
xdata=0802E21FFD85C8CE078A0193 as 1-second data.
offset  bytes   description
Table A.1: An example of the ASCII data format of the CFH sensor, for the case
xdata=0802E21FFD85C8CE078A0193 as 1-second data.
offset  bytes   description
 0      1       Instrument_type = 08 (=CFH)
 1      1       Instrument_number = 02 (Second instrument in the daisy chain)
 2      3       Mirror temperature = E21FFD
 5      3       Optics voltage = 85C8CE
 8      2       Optics temperature = 078A
10      2       CFH Battery = 0193
```
but no derived values. Enough for raw data output, though.
I found 3 examples
https://www.gruan.org/gruan/editor/documents/gruan/GRUAN-TN-8_GRUAN-Monitor-MW41.pdf
(p.13)
```
CFH xdata=0803DC5EF086C244078601A5
08 03
DC5EF0 : Tmir
86C244 : Vopt
0786   : Topt   // temp optics: 34.42C ?
01A5   : Vbat   // battery    : 12.33V ?
frostpoint: 23.56C
testpoint: 2.63201V
```
https://www.gruan.org/gruan/editor/documents/gruan/GRUAN-TN-8_GRUAN-Monitor-MW41-and-Vaisala-RS41-Additional-Sensor-Interface_v1.0.pdf
(p.7)
```
CFH xdata=0802DD44D58A7B320567018E
08 02
DD44D5 : Tmir
8A7B32 : Vopt
0567   : Topt   // temp optics: 39.72C ?
018E   : Vbat   // battery    : 11.66V ?
frostpoint: 24.22C
testpoint: 2.70471V
```
(p.8)
```
CFH xdata=0802A2D58B8050FE08290174
08 02
A2D58B : Tmir
8050FE : Vopt
0829   : Topt   // temp optics: 32.83C ?
0174   : Vbat   // battery    : 10.90V ?
frostpoint: -19.15C
testpoint: 2.50618V
```
Vbat <-> battery <-> is not exactly linear, but close. Not sure if "testpoint" and optics_voltage are related, "frostpoint" might be derived from mirror_temperature (and other values), there might be calibration involved? And temp_optics increases with lower values of Topt? Assuming the examples are actual values.

**Comment by pavolgaj** [comment]
Some descriptions of measured values are in https://www.gruan.org/gruan/editor/documents/gruan/GRUAN-TN-11_GruanToolRs92_v1.0_2020-10-01.pdf (page 33). And there "FrostPoint" = "MirrorTemperature".

I found the coeficients for voltages according to examples:
* testpoint/optics_voltage = int_value/3355443.0
* battery_voltage = int_value/34.136

and for temperatures:
* optics_temp = (5452.847-int_value)/102.4637
* mirror_temp = (int_value-12362317.72)/88293.637

Where `int_value` is value decoded for XDATA. But, these numbers are only the results of a linear fit. I don't know if they're correct and universal for all CFH devices :(

Edit: Just tested on these data: https://github.com/rs1729/RS/pull/43#issuecomment-1029901364. Relation for 'optics_temp' seems to be more or less good - temperatures are always close to 34C. But, the calculation of 'mirror_temp' is wrong -  it returns temperature around -88C.

**Comment by rs1729** [comment]
More examples hidden in the GRUAN documents, thanks!
In the 3 examples above, for the Vbat quotient I got 0x1A5/12.33=34.144, 0x18E/11.66=34.134, 0x174/10.9=34.128, could be rounding errors (0.66 and 0.33 could indicate some factor 3 involved), but with this resolution I would expect a bit more.
Really strange these magic numbers, there is enough space, no need to squeeze the values. Perhaps raw values.
Don't understand why scientific instruments are not better/transparently documented... Maybe there exists documentation, but I hear CFH is closed source?

**Comment by LukePrior** [comment]
Yeah I never found the correct coefficients for all the CFH fields so restrained from adding it to the JS decoder and wiki. If anyone can figure it out fully I would be happy to include it.

**Comment by pavolgaj** [comment]
I found out that RS41Tracker (http://escursioni.altervista.org/Radiosonde/) can decode also CFH data. Unfortunately, I don't have any RAW data with CFH to test.

**Comment by LukePrior** [comment]
I reached out to the developer of that program for any information he might have about the various xdata instruments but I haven't heard anything back.

**Comment by rs1729** [comment]
I would prefer having documentation from the  developer or manufacture of the instruments.

**Comment by JRus-design** [comment]
Maybe you have yet this documentation:

https://www.en-sci.com/wp-content/uploads/2020/06/Cryogenic-Frost-Point-Hygrometer-Handbook-2018.pdf

https://www.en-sci.com/wp-content/uploads/2020/06/Cryogenic-Frost-Point-Hygrometer-Operator-Manual-2016.pdf

Best regards,

Javier

**Comment by rs1729** [comment]
Is there a protocol description (except for the modulation parameters)?
In the new En-Sci documents I didn't find any protocol descriptions, the ECC Ozonesonde manual is an old version, not on the website.
Or maybe I just didn't see it.
EDIT:
The protocol description in the older ECC Ozonesonde manual was specific to iMet-1-RSB. I think En-Sci is not only for iMet now, but the xdata part is basically the same, hence they could describe the xdata output of the interface.
