### ISSUE TITLE
Can't seem to get iqserver/iqclient work

### ISSUE THREAD

**Issue by flux242** [rs1729/RS#22]
I've compile the server and the client as well as recompiled all decoders in demod/mod

The server is started normally
```
IF : 48000
dec: 50
bps: 32
waiting on port 1280
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Sampling at 2400000 S/s.
Tuned to 402500000 Hz.
Tuner gain set to automatic.
Reading samples in async mode...
Allocating 15 zero-copy buffers
<0: ADD f=-0.0833>
waiting on port 1280
```
remark1: I'm sending -0.08333333 and if you scanf it into -0.0833 then you get 80 Hz offset. 
remark2: I'm not sure if the sign is correct. If my target freq is above the tuner one then I want baseband be shifted left, so the rate param should be negative. Looks like it's the other way around here. But it doesn't matter

I'm starting the client the following way provided very strong rs41 signal at 402300000
```
#!/bin/bash

calc_bandpass_param()
{
  #$1 = $SONDE_SIGNAL_BANDWIDTH
  #$2 = $DEMODULATOR_OUTPUT_FREQ

  awk -v sb=$1 -v ofr=$2 'BEGIN{printf("%.8f\n", sb/ofr)}'
}


TUNER_FREQUENCY=402500000
TARGET_FREQUENCY=402300000
TUNER_SAMPLE_RATE=2400000

freq=$(calc_bandpass_param "$((TARGET_FREQUENCY-TUNER_FREQUENCY))" "$TUNER_SAMPLE_RATE")
echo "freq: $freq"

./iq_client --freq "$freq" | tee >(./rs41mod -vx --IQ 0.0 - 48000 32) |
./csdr fmdemod_quadri_cf | ./csdr limit_ff | ./csdr convert_f_s16 |
sox -t raw -esigned-integer -b 16 -r 48000 - -b 8 -c 1 -t wav - highpass 10 gain +5 |
aplay -r 48000 -f S8 -t wav -c 1 -B 500000 &> /dev/null
```
here is the output:
```
freq: -0.08333333
sox WARN wav: Length in output .wav header will be wrong since can't seek to fix it
client: 0
sr: 48000
bsp: 32
IF: 48000
dec: 1
^Csox WARN highpass: highpass clipped 1922 samples; decrease volume?
sox WARN gain: gain clipped 10594 samples; decrease volume?
sox WARN dither: dither clipped 9324 samples; decrease volume?
```

rs41mod doesn't output anything but you can listen what my csdr demodulator outputs
[https://ufile.io/0olggr9x](url)
Don't know how long this file be available

But it sounds to be off the target frequency

**Comment by flux242** [comment]
Interesting, it's about 15kHz off the target frequency and I can correct the offset by subtracting 15kHz from the target frequency

**Comment by flux242** [comment]
ahhh, I forgot to set the ppm for the dongle.
nevermind

**Comment by rs1729** [comment]
Just uploaded a small python script `plot_fft.py` to display the raw FFT data
`python plot_fft.py <db_fft.txt>`
Two x-axis, above -0.5 .. +0.5 and below the relative frequency in Hz.
The freq parameter is where the signal is in the spectrum, the translation would be the opposite direction.
Lower frequencies are in the negative direction.
If you use saved IQ-files, it can happen, that the IQ-data is swapped, e.g. with older sdrsharp-versions.

I have a small stripped down peak-scan tool, no time today to clean it up, but will try to upload it soon.

If you have a rtlsdr-stick with constant ppm or the rtl-sdr v3, the frequencies should be at the expected offsets.
The dvb-t-rtlsdr-sticks with cheap oscillators can vary with temperature.
Probably best to have a good scan tool that outputs the relative frequencies of interesting signals.

**Comment by flux242** [comment]
as a side comment:
all non modified rtl-sdr dongles I have, have constant ppm. I just let it work for couple of minutes and then the ppm won't drift anymore as the dongle riches its working temperature. So all those scary stories about non having TXCOs in them is pure marketing from my point of view.

**Comment by rs1729** [comment]
Yes, my old dvb-t sticks are also reliable and don't drift after warm-up. Only one I think was behaving strange. The only thing is to remember the ppm offsets of the individual sticks... sometimes I get a bit confused. ;)

**Comment by flux242** [comment]
OK, I have patched my script to use iqserver/iqclient concept and it seems to work at least for 2 channels at the same time. I haven't tested the fft scans over a client yet but maybe I'll open another feature request about sending power scanner results to a client. Please close this issue

**Comment by flux242** [comment]
oh, i've noticed that there's a 'close button' so I can close the issue myself
