### ISSUE TITLE
RS41 SGP Pressure Sensor Value

### ISSUE THREAD

**Issue by JRus-design** [rs1729/RS#25]
Hi,
I´m using your decoder with radiosonde_auto_rx and in the log of the sounding the value of the pressure sensor is not present. 
It´s not implemented yet? Because the model of the sonde -SGP (with sensor pressure) is well detected.
Thanks a lot for your devellopment and efforts.
Javier

**Comment by rs1729** [comment]
No, currently there are no plans to implement it.
Only the station pressure is output (-vv).

**Comment by rs1729** [comment]
Update:
Included the pressure calculations from DF9DQ (@einergehtnochrein)
https://github.com/einergehtnochrein/ra-firmware/tree/master/src/rs41
that can also be found in the RS-fork
https://github.com/stsst/RS
