### ISSUE TITLE
rawhex input

### ISSUE THREAD

**Issue by pavolgaj** [rs1729/RS#30]
Is it possible to use the raw file as input for different decoders as rs41mod? There is --rawhex option in rs41mod. But, I couldn't find it in other decoders - m10mod, mXXmod, rs92mod etc.
During sounding, I use option -r to write output to the raw file. And after sounding ends, I decode data to readable data or a JSON file.

**Comment by rs1729** [comment]
Yes, I wanted to add it for m10/mXX.
The older https://github.com/rs1729/RS/blob/master/rs92/rs92gps.c has also this option, maybe I can include it in rs92mod such that you have json-output.

**Comment by rs1729** [comment]
Added m10mod/mXXmod rawhex input (to test branch).
update:
Added rawhex input to rs92mod.
remark:
dfm09mod is problematic, the raw output would need time marks if not done with with --dist option to get reliable frames.
