### ISSUE TITLE
RS41 temperature and humidity calculation.

### ISSUE THREAD

**Issue by tom2238** [rs1729/RS#41]
Hi. I'm trying to find how to read temperature and humidity directly from the sonde (custom firmware). In file rs41ptu.c I found function to calculate temperature (and humidity too). I would like to know where you got information about calculation and coefficients values. Maybe from sensor manufacturer datasheet?

**Comment by rs1729** [comment]
The raw sensor data was not hard to find.
The coefficients for calculating the raw temperature and calibration is bit more involved. This was found by comparing the raw data to the sounding data that can be found e.g. at
http://weather.uwyo.edu/upperair/bufrraob.shtml
The RS41 datasheet says that the temperature sensor type is "Platinum Resistor". In general temperature data is no so complicated, at least in hindsight after you have looked through the data many times.

Humidity sensors have a more complex behavior, in particular it depends also on temperature.
Vaisala calls its humidity sensor "Humicap", the RS41 datasheet says it is of "Type: Thin-Film Capacitor".
In rs41ptu.c there is a rough empirical approximation. In
https://github.com/rs1729/RS/blob/master/demod/mod/rs41mod.c
you can find a more accurate calculation.

**Comment by tom2238** [comment]
Thanks. Currently I am trying to measure frequency at input pin with timer using BluePill board. In next step I will try measure frequency of ring oscillator (sensors + reference). Calculation of gain and offset are interesting for me. This equation:" T = (p[0] + p[1]*R + p[2]*R*R + c[1])*(1.0 + c[2]); " looks like as normal calculation (from R [ohm] to T [degC]) for PT100 or PT1000 (with calibration here).

**Comment by rs1729** [comment]
Yes, PT1000.
Here are some remarks (in german)
https://www.fingers-welt.de/phpBB/viewtopic.php?t=43&start=2400#p198064
