### ISSUE TITLE
m10ptu show invalid frames 

### ISSUE THREAD

**Issue by modem2k2** [rs1729/RS#46]
Using m10ptu sometimes i get incorrect readings (time, date, alt and lat/lon), this does not happen with other decoders like sondemonitor. I wonder if it would be possible to improve the performance or extra frame checks. I don't see that the decoder has any command line switch, would it be possible to show only the valid frames?

```
(W 2218) Di 2022-07-12 (14:14:50)  lat: 39.XXXXXX  lon: -1.XXXXXX  alt: 878.31
 (W 2218) Di 2022-07-12 (14:14:52)  lat: 39.XXXXXX  lon: -1.XXXXXX  alt: 872.00
 (W 2218) Di 2022-07-12 (14:14:55)  lat: 39.XXXXXX  lon: -1.XXXXXX  alt: 862.64
 (W 272) Di 1985-03-26 (14:14:59)  lat: 39.XXXXXX  lon: -2.XXXXXX alt: 1682.48
 (W 272) Di 1985-03-26 (14:15:18)  lat: 39.XXXXXX  lon: -2.XXXXXX alt: 1261.89
 (W 2218) Di 2022-07-12 (14:15:33)  lat: 39.XXXXXX  lon: -1.XXXXXX  alt: 728.86
 (W 2218) Di 2022-07-12 (14:15:39)  lat: 39.XXXXXX  lon: -1.XXXXXX  alt: 657.37
 (W 1088) Di 2000-11-14 (14:15:57)  lat: 25.XXXXXX  lon: -2.XXXXXX alt: 61.82
 (W 544) Mo 1990-06-11 (23:37:43)  lat: 30.XXXXXX  lon: -2.XXXXXX  alt: 1203.45

```

**Comment by rs1729** [comment]
The decoding in `RS/m10/m10ptu.c` is kept very simple. If the signal is not very strong, use either a low pass filter or use the option `-b` or `-b2`. Use option `-vv`to see the serial number and the checksum result ([OK] or [NO]) for each frame; this way you could filter/grep only the OK-frames. Option `--ptu` gives you the temperature values. Then there is the option `-c` for colored output.

However,
the m10ptu-decoder is old and deprecated. Consider using `m10mod.c` in
https://github.com/rs1729/RS/tree/master/demod/mod
See the README there, there is also a Makefile.
Recommended options for M10:
`./m10mod -vv --ptu -c <audio.wav>`

**Comment by modem2k2** [comment]
Thanks for the quick reply, I will try these tips. :)
