### ISSUE TITLE
weathex sonde

### ISSUE THREAD

**Issue by Joanvoo** [rs1729/RS#56]
Hi, i try today decode the Weathex radiosonde but it was not possible.
Maybe a newer version?
bandwith = 60KHz frequency 403.700 
a small piece of a another sonde is through it in the beginning (404.200)
a sample off the whole launch in audio wav format:

https://www.dropbox.com/scl/fi/upfigqkrovw8syaiag1kg/weathexsonde.zip?rlkey=q4v24ia7yvi99lpdtodevyrd8&st=asbidr15&dl=0

**Comment by rs1729** [comment]
This was launched in Utrecht?
```
 (2023112215)  [ 5437]  13:51:24  alt: 272.0  lat: 51.9709  lon: 4.9280   [OK]
 (2023112215)  [ 5439]  13:51:26  alt: 286.9  lat: 51.9709  lon: 4.9281   [OK]
 (2023112215)  [ 5441]  13:51:28  alt: 302.5  lat: 51.9710  lon: 4.9283   [OK]
 (2023112215)  [ 5442]  13:51:29  alt: 308.8  lat: 51.9710  lon: 4.9284   [OK]
[...]
```
Looks like the Weathex 301D that was used at UAII 2022 in Lindenberg.
You can try this decoder
https://github.com/rs1729/RS/blob/test/uaii2022/uaii20220812_405400.c
```
gcc uaii20220812_405400.c -o wxr_uaii2022
./wxr_uaii2022 -i weathexsonde.wav
```

Don't know what the difference is between these two Weathex radiosondes. I believe they both are called WxR 301D, the signal is similar.

**Comment by Joanvoo** [comment]
thanks thats works position is correct from KNMI

**Comment by rs1729** [comment]
`weathex/weathex301d.c` can now also decode this variant (with PN9), but not automatically;
you need the additional option `--pn9`.
