### ISSUE TITLE
Feature Reqest: decoding other parameter for meisei

### ISSUE THREAD

**Issue by digrx** [rs1729/RS#6]
Is it possible to add decoding for other data such as temperatur, humidity, and air pressure
for Meisei ims100 radiosonde ?

**Comment by rs1729** [comment]
I don't know much about Meisei radiosondes. Someone provided some (short) recordings of test soundings of two different Meisei radiosondes at Lindenberg in Oct 2014, just enough to figure out some basic data. But I don't even know for sure that one of them was the iMS-100 (or which one).

I hear that they are used in Turkey, Mexico and probably Japan?
